from django.conf.urls import url 
from cpccs import views 
 
 
urlpatterns = [ 
    url(r'^sectores/$',  
        views.SectorList.as_view(),  
        name=views.SectorList.name),
    url(r'^ciudades/$',  
        views.CiudadList.as_view(),  
        name=views.CiudadList.name),
    url(r'^estados-civiles/$',  
        views.EstadoCivilList.as_view(),  
        name=views.EstadoCivilList.name),
    url(r'^instituciones/$',  
        views.InstitucionList.as_view(),  
        name=views.InstitucionList.name),
    url(r'^nacionalidades/$',  
        views.NacionalidadList.as_view(),  
        name=views.NacionalidadList.name),		
    url(r'^niveles-educacion/$',  
        views.NivelEducacionList.as_view(),  
        name=views.NivelEducacionList.name),
    url(r'^ocupaciones/$',  
        views.OcupacionList.as_view(),  
        name=views.OcupacionList.name),
    url(r'^predenuncias/$',  
        views.PreDenunciaList.as_view(),  
        name=views.PreDenunciaList.name),
    url(r'^provincias/$',  
        views.ProvinciaList.as_view(),  
        name=views.ProvinciaList.name),
    url(r'^reclamos/$',  
        views.ReclamoList.as_view(),  
        name=views.ReclamoList.name),
    url(r'^regiones/$',  
        views.RegionList.as_view(),  
        name=views.RegionList.name),    
    url(r'^usuarios/$',  
        views.UsuarioList.as_view(),  
        name=views.UsuarioList.name), 
    url(r'^$', 
        views.ApiRoot.as_view(), 
        name=views.ApiRoot.name), 
] 