# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ciudad',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'estadocivil',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('representante', models.CharField(max_length=255)),
                ('competencia', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'institucion',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'nacionalidad',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='NivelEducacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'niveleducacion',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ocupacion',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PreDenuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodenuncia', models.CharField(max_length=1)),
                ('generodenunciante', models.CharField(max_length=1)),
                ('descripcioninvestigacion', models.CharField(max_length=255)),
                ('generodenunciado', models.CharField(max_length=1)),
                ('funcionariopublico', models.CharField(blank=True, default='', max_length=255)),
                ('estadocivildenunciante', models.ForeignKey(db_column='estadocivildenuncianteid', on_delete=django.db.models.deletion.CASCADE, to='cpccs.EstadoCivil')),
                ('institucionimplicada', models.ForeignKey(db_column='institucionimplicadaid', on_delete=django.db.models.deletion.CASCADE, to='cpccs.Institucion')),
                ('nacionalidaddenunciante', models.ForeignKey(db_column='nacionalidaddenuncianteid', on_delete=django.db.models.deletion.CASCADE, to='cpccs.Nacionalidad')),
                ('niveleducaciondenunciante', models.ForeignKey(db_column='niveleducaciondenuncianteid', on_delete=django.db.models.deletion.CASCADE, to='cpccs.NivelEducacion')),
                ('ocupaciondenunciante', models.ForeignKey(db_column='ocupaciondenuncianteid', on_delete=django.db.models.deletion.CASCADE, to='cpccs.Ocupacion')),
            ],
            options={
                'db_table': 'predenuncia',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'provincia',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombresapellidosdenunciante', models.CharField(max_length=255)),
                ('tipoidentificacion', models.CharField(max_length=255)),
                ('numidenti', models.CharField(max_length=255)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('nombresapellidosdenunciado', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, default='', max_length=255)),
                ('cargo', models.CharField(blank=True, default='', max_length=255)),
                ('comparecer', models.BooleanField(default=False)),
                ('documentores', models.BooleanField(default=False)),
                ('identidadreservada', models.BooleanField(default=False)),
                ('resideextrangero', models.BooleanField(default=False)),
                ('ciudaddeldenunciado', models.ForeignKey(db_column='ciudaddeldenunciadoid', on_delete=django.db.models.deletion.CASCADE, related_name='ciudaddenunciado', to='cpccs.Ciudad')),
                ('ciudaddeldenunciante', models.ForeignKey(db_column='ciudaddeldenuncianteid', on_delete=django.db.models.deletion.CASCADE, related_name='ciudaddeldenunciante', to='cpccs.Ciudad')),
                ('institucionimplicada', models.ForeignKey(db_column='insttitucionimplicadaid', on_delete=django.db.models.deletion.CASCADE, to='cpccs.Institucion')),
                ('provinciadenunciado', models.ForeignKey(db_column='provinciadenunciadoid', on_delete=django.db.models.deletion.CASCADE, related_name='provinciadenunciado', to='cpccs.Provincia')),
                ('provinciadenunciante', models.ForeignKey(db_column='provinciadenuncianteid', on_delete=django.db.models.deletion.CASCADE, related_name='provinciadenunciante', to='cpccs.Provincia')),
            ],
            options={
                'db_table': 'reclamo',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'region',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('control', models.CharField(max_length=5)),
                ('mensaje', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sector',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'usuario',
                'ordering': ('nome',),
            },
        ),
    ]
